### ISSUE TITLE
Feature Request: Passing header with requests to azure.

### ISSUE THREAD

**Issue by joneschmitz** [webdevops/azure-loganalytics-exporter#2]
I would like to request for an option to include a "cache-control: no-cache" header in the request(s) being sent to azure. Azure loganalytics has a server-side caching interval of 2 minutes which can be managed by the http request header "cache-control". This would allow for near real-time metrics to be produced from this exporter when using scraping intervals of 1m or 2m. Such an option would increase its usability in observability solutions and give the exporter better control over the data it produces.

Source: [https://docs.microsoft.com/en-us/azure/azure-monitor/logs/api/cache](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/api/cache)

**Comment by mblaschke** [comment]
can you try `webdevops/azure-loganalytics-exporter:main`?

**Comment by joneschmitz** [comment]
![loganalytics](https://user-images.githubusercontent.com/51449182/164363579-0fdcd886-01fd-4438-ac4f-5994fc782755.png)
(Left is the Master branch as of your reply, right is of a commit several days ago before the multi workspace option was added to config.yaml parser)

It appears to be pulling data now at an interval smaller than 2 minutes.

**Comment by mblaschke** [comment]
so we can close this feature request?
will be released with the next version :)

**Comment by joneschmitz** [comment]
Yes. Thank you.
