### ISSUE TITLE
How to define timespan 'Set in query'

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-loganalytics-exporter#3]
Hi,

I would like to know how I can define the timespan 'set in query' like this:

![image](https://user-images.githubusercontent.com/1560587/175930833-68c7474e-3452-49c1-b9b6-48756581fe1b.png)

**Comment by jkroepke** [comment]
It looks like omit the timespan value should be the solution here

**Comment by mblaschke** [comment]
can you try it with container image `webdevops/azure-loganalytics-exporter:main`?

**Comment by mblaschke** [comment]
released with `22.9.0`
